border-color = [214, 73, 55]

[font]
file = "/usr/share/fonts/noto/NotoSansMono-Regular.ttf"
color = [214, 73, 55]

[keys]
squares = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "[",
  "]",
  ";",
  "'",
  ",",
  ".",
  "/",
  "\\",
  "`",
  "1",
  "9",
  "0",
  "-",
  "="
]
