[colors]
border = "#00BFFF"
font = "#00BFFF"

[keys]
#
# Key to exit the application:
#
# default: Escape
exit = "Escape"
#
# Minimum tile keys required: 8, up to whatever you want.
#
# More tile keys will reduce the number of required key strokes.
#
# N.b: duplicates are not allowed.
tiles = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "[",
  "]",
  ";",
  "'",
  ",",
  ".",
  "/",
  "\\",
  "`",
  "1",
  "9",
  "0",
  "-",
  "="
]
